alias la='ls -a'
alias ll='ls -al'
alias vv='vim ~/.vimrc'
alias vr='vim ~/.bashrc'
alias vp='vim ~/.profile'
alias sp='source ~/.profile'
alias sh='/usr/local/bin/bash'
alias du='du -sh'

alias app='bash app.sh'
alias mcc='mvn clean compile'
alias sbr='mvn spring-boot:run'
alias ccr='mcc && sbr'
alias mcp='mvn clean package'
alias http='http --verify=no'
alias xurl='curl -x 127.0.0.1:7890'
alias my='mycli -uroot -h127.0.0.1'

alias gae='git add . && git ce'
alias git_first_commit='git cm "initial commit (empty)" --allow-empty'
alias use_ali='HOMEBREW_BOTTLE_DOMAIN=https://mirrors.aliyun.com/homebrew/homebrew-bottles'
